services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh start.sh
    volumes:
      - /home/docker/data/carpe/:/code:rw
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.carpe.rule=Host(`carpe-calendar.kapucl.be`) || Host(`agenda.carpestudentem.be`)"
      - "traefik.http.services.carpe.loadbalancer.server.port=8000"
      - "traefik.http.routers.carpe.tls=true"
      - "traefik.http.routers.carpe.tls.certresolver=http"
      - "traefik.http.routers.carpe.entrypoints=websecure"
    networks:
      - external
networks:
  external:
    name: external
    external: true